@extends('layouts.app')

@section('title', 'Privacy Policy - Smartest Reviews')
@section('description', 'Read our privacy policy to understand how we collect, use, and protect your personal information.')

@section('content')
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Main Content -->
        <div class="lg:col-span-2">
            <article class="bg-white rounded-lg shadow-lg p-8">
                <h1 class="text-4xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
                
                <div class="prose max-w-none">
                    <p class="text-lg text-gray-700 mb-6">
                        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                    </p>

                    <p class="text-gray-700 mb-8">
                        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                    </p>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">Interpretation and Definitions</h2>
                    
                    <h3 class="text-xl font-semibold text-gray-900 mb-3">Interpretation</h3>
                    <p class="text-gray-700 mb-4">
                        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                    </p>

                    <h3 class="text-xl font-semibold text-gray-900 mb-3">Definitions</h3>
                    <p class="text-gray-700 mb-4">
                        For the purposes of this Privacy Policy:
                    </p>
                    <ul class="list-disc list-inside text-gray-700 space-y-2 mb-8">
                        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Smartest Reviews.</li>
                        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                        <li><strong>Service</strong> refers to the Website.</li>
                        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
                        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                        <li><strong>Website</strong> refers to Smartest Reviews, accessible from smartestreviews.com</li>
                        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                    </ul>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">What Information Do We Collect?</h2>
                    <p class="text-gray-700 mb-4">
                        We collect information you provide directly to us, such as when you create an account, subscribe to our newsletter, or contact us. This may include:
                    </p>
                    <ul class="list-disc list-inside text-gray-700 space-y-2 mb-8">
                        <li>Personal information you knowingly choose to disclose</li>
                        <li>Website use information collected for general data purposes</li>
                        <li>Email addresses for newsletter subscriptions</li>
                        <li>Contact information when you reach out to us</li>
                    </ul>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">How We Use Your Information</h2>
                    <p class="text-gray-700 mb-4">
                        We use the information we collect to:
                    </p>
                    <ul class="list-disc list-inside text-gray-700 space-y-2 mb-8">
                        <li>Provide, maintain, and improve our services</li>
                        <li>Send you newsletters and updates (with your consent)</li>
                        <li>Respond to your comments and questions</li>
                        <li>Analyze website usage to improve user experience</li>
                        <li>Comply with legal obligations</li>
                    </ul>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">Cookies and Tracking</h2>
                    <p class="text-gray-700 mb-4">
                        We use cookies and similar tracking technologies to track activity on our website and hold certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
                    </p>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">Data Security</h2>
                    <p class="text-gray-700 mb-4">
                        We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet or electronic storage is 100% secure.
                    </p>

                    <h2 class="text-2xl font-bold text-gray-900 mb-4">Contact Us</h2>
                    <p class="text-gray-700 mb-4">
                        If you have any questions about this Privacy Policy, please contact us at:
                    </p>
                    <div class="bg-gray-50 rounded-lg p-4">
                        <p class="text-gray-700"><strong>Email:</strong> privacy@smartestreviews.com</p>
                        <p class="text-gray-700"><strong>Address:</strong> Smartest Reviews, Privacy Department</p>
                    </div>
                </div>
            </article>
        </div>

        <!-- Sidebar -->
        <div class="lg:col-span-1">
            <!-- Search -->
            <div class="bg-white rounded-lg shadow-md p-6 mb-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4">SEARCH</h3>
                <form action="{{ route('search') }}" method="GET" class="flex">
                    <input type="text" name="q" placeholder="Search products..." 
                           class="flex-1 px-3 py-2 border border-gray-300 rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent text-sm">
                    <button type="submit" 
                            class="bg-pink-500 text-white px-3 py-2 rounded-r-md hover:bg-pink-600 transition-colors text-sm font-medium whitespace-nowrap">
                        SEARCH
                    </button>
                </form>
            </div>

            <!-- Our Sources -->
            <div class="bg-white rounded-lg shadow-md p-6">
                <h3 class="text-lg font-semibold text-gray-900 mb-4">Our Sources</h3>
                <div class="space-y-4">
                    @forelse($sources as $source)
                        @php
                            $hasUrl = $source->url && !empty($source->url);
                            $tag = $hasUrl ? 'a' : 'div';
                        @endphp
                        <{{ $tag }} 
                            @if($hasUrl) href="{{ $source->url }}" target="_blank" rel="noopener noreferrer" @endif
                            class="flex items-center space-x-3 {{ $hasUrl ? 'hover:opacity-80 transition-opacity cursor-pointer' : '' }}">
                            <div class="w-12 h-12 rounded-lg flex items-center justify-center" style="background-color: {{ $source->color }}">
                     nhung           @if(strpos($source->icon, 'fa-') === 0 || strpos($source->icon, 'fas ') === 0)
                                    <i class="{{ $source->icon }} text-white text-lg"></i>
                                @else
                                    <span class="text-white font-bold text-lg">{{ $source->icon ?? substr($source->name, 0, 1) }}</span>
                                @endif
                            </div>
                            <div>
                                <h4 class="font-semibold text-gray-900">{{ $source->name }}</h4>
                                @if($source->description)
                                    <p class="text-sm text-gray-600">{{ $source->description }}</p>
                                @endif
                            </div>
                        </{{ $tag }}>
                    @empty
                        <p class="text-sm text-gray-500">No sources available.</p>
                    @endforelse
                </div>
            </div>
        </div>
    </div>
</div>
@endsection